# Generated by Django 4.2.6 on 2023-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
